channels:
  - conda-forge
  - "bioconda/label/cf201901"
dependencies:
  - gsl=2.6
  - flex
  - bison
  - mcl
  - python=3.8.5
  - numpy
  - pip
  - pip:
    - networkx
    - openpyxl
    - pyarrow
    - pandas
    - matplotlib
    - rst2pdf
    - joblib
