#!/bin/bash

#FIXME: add include_path & library_path for binder image only, may not be necessary if gsl is installed locally
CPLUS_INCLUDE_PATH=${NB_PYTHON_PREFIX}/include
export CPLUS_INCLUDE_PATH
LIBRARY_PATH=${NB_PYTHON_PREFIX}/lib
export LIBRARY_PATH
LD_LIBRARY_PATH=${NB_PYTHON_PREFIX}/lib
export LD_LIBRARY_PATH

cd dependencies/Model_Checking/dishwrap_v1.0/dishwrap
make
cd ../monitor
make
